language: python
dist: bionic

python:
  - '3.7'

before_install:
  - sudo rm -f /etc/boto.cfg

env:
  - AWS_DEFAULT_REGION=us-east-1 DYNAMODB_TABLE_K8_CLUSTERS=hyper-kube-config-test

install:
  - pip install -r requirements.txt
  - pip install -r tests/requirements.txt

stages:
  - lint
  - test
  - deploy

jobs:
  include:
    - stage: lint
      name: linting
      script:
        - flake8 *.py tests cli/kubectl-hyperkube
    - stage: test
      name: test
      dist: bionic
      python: 3.7
      script: 
        - python -m unittest discover -v -s tests/ -p "*.py"
    - stage: deploy
      name: deploy
      if: tag IS present
      provider: pypi
      user: sepulworld
      password:
        secure: wLcSbt9EiGUU+R7ad6JwG0aREpq13rJUive6TgaqP/NJ3gFY04rvl22Dh4A1qhbaaxsTrQRp+E7n43/rUwQ46GR9wv4eg73z+2+krwd7JvhoDVQv5JJxSMjuatM6Zl060O8kWZd8cVwQkfLcStIVgIiH8EggkJSsBQl+dRuZ4lJt8bRDU+FZIaUzqkWBrwEgqT5EtJsj2A8EWqAxXMtdra7oFq/thcNWLNOnSY3l14Vtx0YDH1WnWUcBCQuLciL4Xd6av3koQSNqH6TPxWaS5VR3fLp7jkDdMONPNosFXLzhXm5g8PILMuIBqLwRPfjcFmIQZ/jIwQM2jl24ojwA3CNw40oZ341lAonSxe86vhYTg76+URTD5fSc7W5nJ483arUzl+QEhfNVPnFPhZkcyvtW2dro8ZpBzZscZD2oRX5SfNLbbyFunwl6b0s5oxCSPP4vpTiHjDRUgo5CK9J2rGuDfuHJ3B07Wj55au9IpMukEr8/0rrfh6JopV+frxujX9MI7taqhpiXEfDQrfySzpfwgr7vnTc1itAZlvpZj8Ri6+ZYDD0ISWYDBnz9hz7u897Yia+VIzXog/1m+sCehPm6kMqblBiBceGzN8L9IivZgG6j2zkoF2xlvZhatDvcCmiXbtTuZZ05bSHpB9xcIwzlFdLYEFIQWA7N+FGGmZs=
