service: hyper-kube-config

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    noDeploy: []
    dockerizePip: true

provider:
  name: aws
  runtime: python3.6
  region: us-west-2
  apiKeys:
    - ${self:service}-${opt:stage, self:provider.stage}-key

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "secretsmanager:*"
      Resource: "arn:aws:secretsmanager:*:*:secret:hyper-kube-config*" 
    - Effect: "Allow"
      Action:
        - "secretsmanager:ListSecrets"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "arn:aws:dynamodb:*:*:table/hyper-kube-config*"

  environment:
    DYNAMODB_TABLE_K8_CLUSTERS: ${self:service}-${opt:stage, self:provider.stage}-clusters

  stackTags:
    Environment: ${opt:stage}
    Team: ${opt:team}
    Owner: ${opt:owner}
    Product: ${opt:product}
    Service: "hyper-kube-config"

functions:
  add_cluster:
    handler: add_cluster.add_cluster
    events:
      - http:
          path: clusters/add
          method: post
          private: true
  add_pem:
    handler: pem.add_pem
    events:
      - http:
          path: clusters/add-pem
          method: post
          private: true
  remove_cluster:
    handler: remove_cluster.remove_cluster
    events:
      - http:
          path: clusters/remove
          method: post
          private: true
  remove_pem:
    handler: pem.remove_pem
    events:
      - http:
          path: clusters/remove-pem
          method: get
          private: true
  get_k8s_config_object:
    handler: get_k8_config.get_k8_config
    events:
      - http:
          path: clusters/get-k8-config
          method: get
          private: true
  get_all_k8s_config:
    handler: get_k8_config.get_all_k8_configs
    events:
      - http:
          path: clusters/get-all-k8-configs
          method: get
          private: true
  get_pem:
    handler: pem.get_pem
    events:
      - http:
          path: clusters/get-pem
          method: get
          private: true
  list_clusters:
    handler: list_clusters.list_clusters
    events:
      - http:
          path: clusters/list
          method: get
          private: true
  cluster_status:
    handler: cluster_status.cluster_status 
    events:
      - http:
          path: clusters/cluster-status
          method: get
          private: true
  clusters_per_environment:
    handler: cluster_status.clusters_per_environment
    events:
      - http:
          path: clusters/clusters-per-environment
          method: get
          private: true
  set_cluster_environment:
    handler: cluster_status.set_cluster_environment
    events:
      - http:
          path: clusters/set-cluster-environment
          method: get
          private: true
  set_cluster_status:
    handler: cluster_status.set_cluster_status
    events:
      - http:
          path: clusters/set-cluster-status
          method: get
          private: true
          
resources:
  Resources:
    KubeAuthStoreClustersDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 3
        TableName: '${self:provider.environment.DYNAMODB_TABLE_K8_CLUSTERS}'
